New version should work, lacks some extra jq features such as while (|), ',', and '[]' will add in future -- maybe

diff --git a/jp b/jp
--- a/jp
+++ b/jp
@@ -1,17 +1,66 @@
 #!/bin/sh
 orgtemp="$(mktemp)"
 temp="$(mktemp)"
+spatemp="$(mktemp)"
+# idtemp="$(mktemp)"
 cat > "$orgtemp" # jp is meant to read from a pipe
-grep "${1#.}" "$orgtemp" > "$temp"
+grep '\s*"' -m 1 < "$orgtemp" > "$spatemp"
+IFS='"'; read -r spa ex < "$spatemp" # set space count
+grep "^${spa}"'"'"${1#.}"'"' "$orgtemp" > "$temp"
+head () {
 if ! grep -q "{" "$temp"; then
 	echo "$(grep "${1#.}" "$temp")" > "$temp"
 	sed 's/[[:space:]]//g' -i "$temp"
-	IFS=':' read -r var val < "$temp"
-	echo "$val"
+	IFS=':'; read -r var val < "$temp"
+	case "$val" in
+		"")
+			echo "Whoops!! Can't find ${1#.}"; exit 1;;
+		*)
+			echo "${val%,}";;
+	esac
 else
-	sed '/'"${1#.}"'/,$!d' "$orgtemp" > "$temp"
-	IFS='"' read -r end ex < "$temp"
+	sed '/^'"${spa}"'"'"${1#.}"'"''/,$!d' "$orgtemp" > "$temp"
+	IFS='"'; read -r end ex < "$temp"
 	sed '/^'"${end}"'\}/q' -i "$temp"
-	cat "$temp" && exit
+	sed 's/"'"${1#.}"'" : {/{/g' -i "$temp"
+	sed 's/^'"${end}"'\}\,/}/g' -i "$temp"
+	sed 's/^'"${end}"'//' -i "$temp"
+	cat "$temp"
 fi
-rm "$temp"
+}
+loop() {
+unset IFS
+for i in $@; do
+	if [ "$i" = "$1" ]; then
+		sed '/^'"${spa}"'"'"${i}"'"''/,$!d' "$orgtemp" > "$temp"
+	else
+		sed '/^'"${spa}"'"'"${i}"'"''/,$!d' -i "$temp"
+	fi
+if ! grep -q "{" "$temp"; then
+	echo "$(grep "${i#.}" "$temp")" > "$temp"
+	sed 's/[[:space:]]//g' -i "$temp"
+	IFS=':'; read -r var val < "$temp"
+	case "$val" in
+		"")
+			echo "Whoops!! Can't find ${i}"; exit 1;;
+		*)
+			echo "${val%,}" > "$temp";;
+	esac
+else
+	IFS='"'; read -r end ex < "$temp"
+	sed '/^'"${end}"'\}/q' -i "$temp"
+	sed 's/"'"${i#.}"'" : {/{/g' -i "$temp"
+	sed 's/^'"${end}"'\}\,/}/g' -i "$temp"
+	sed 's/^'"${end}"'//' -i "$temp"
+fi
+done
+}
+if ! [ $(echo ${1} | awk -F. '{print NF-1}') -gt 1 ]; then
+	head "$1"
+else
+	IFS="."; loop ${1#.}
+	cat "$temp"
+fi
+rm "$temp" -rf
+rm "$orgtemp" -rf
+rm "$spatemp" -rf
